export PYENV_ROOT=$HOME/.pyenv

export PATH=$PYENV_ROOT/bin:$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="nomas"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="mm/dd/yyyy"

plugins=(
  git
  tmux
  osx
  python
  pyenv
)

# trialspark things
export COMPOSE_HTTP_TIMEOUT=120

source /usr/local/etc/profile.d/z.sh
source ~/.alias
source $ZSH/oh-my-zsh.sh
